import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

const webRoot = process.cwd();
const platformRoot = join(webRoot, '..', '..');
const loginPanelPath = join(webRoot, 'components/auth/LoginPanel.tsx');
const headerPath = join(webRoot, 'app/app/_components/app-header.tsx');
const planPagePath = join(webRoot, 'app/app/plan/page.tsx');
const trainingPlanPagePath = join(webRoot, 'app/app/_components/training-plan-page.tsx');
const trainingPlanCalendarPath = join(webRoot, 'app/app/_components/training-plan-calendar.tsx');
const currentWeekRepairPanelClientPath = join(webRoot, 'app/app/_components/current-week-repair-panel-client.tsx');
const calendarStylesPath = join(webRoot, 'app/globals.css');
const calendarPagePath = join(webRoot, 'app/app/calendar/page.tsx');
const accountPagePath = join(webRoot, 'app/app/account/page.tsx');
const adminPagePath = join(webRoot, 'app/app/admin/page.tsx');
const syncStatusPagePath = join(webRoot, 'app/onboarding/sync-status/page.tsx');
const dashboardPagePath = join(webRoot, 'app/app/dashboard/page.tsx');
const appLiveRefreshPath = join(webRoot, 'app/app/_components/app-live-refresh.tsx');
const deviceLocationSyncPath = join(webRoot, 'app/app/_components/device-location-sync.tsx');
const middlewarePath = join(webRoot, 'middleware.ts');
const intervalsConnectPanelPath = join(webRoot, 'components/auth/IntervalsConnectPanel.tsx');
const dashboardScriptPath = '/root/.hermes/profiles/profdecisive/scripts/intervals_dashboard.py';

test('login screen copy and auth-page header chrome match the latest product wording', async () => {
  const [loginPanel, header, registerPage, registerPanel, loginPageSource] = await Promise.all([
    readFile(loginPanelPath, 'utf8'),
    readFile(headerPath, 'utf8'),
    readFile(join(webRoot, 'app/register/page.tsx'), 'utf8'),
    readFile(join(webRoot, 'components/auth/RegisterPanel.tsx'), 'utf8'),
    readFile(join(webRoot, 'app/login/page.tsx'), 'utf8'),
  ]);

  assert.match(loginPanel, /auth-login-card-m3/i);
  assert.match(loginPanel, /auth-login-card-premium/i);
  assert.match(loginPanel, /auth-login-card__header/i);
  assert.match(loginPanel, /auth-login-form/i);
  assert.match(loginPanel, /auth-login-form-premium/i);
  assert.match(loginPanel, /auth-login-submit/i);
  assert.match(loginPanel, /button-primary-premium/i);
  assert.match(loginPanel, /input-premium/i);
  assert.match(loginPageSource, /auth-screen-shell-m3/i);
  assert.match(loginPageSource, /auth-screen-panel-m3/i);
  assert.match(loginPageSource, /auth-invite-row-m3/i);
  assert.match(loginPageSource, /button-secondary-premium/i);
  assert.doesNotMatch(loginPanel, /Simple account login/i);
  assert.doesNotMatch(loginPanel, /Launch auth/i);
  assert.match(header, /const hideNavForAuthScreen = pathname === appRoutes\.login \|\| pathname === appRoutes\.register/i);
  assert.doesNotMatch(header, /Le ciel et la limite/i);
  assert.doesNotMatch(header, /label: 'Configuration'/i);
  assert.match(header, /userDisplayName && userEmail \? `\$\{userDisplayName\} - \$\{userEmail\}`/i);
  assert.match(registerPage, /validateInviteCodeRecord/i);
  assert.match(registerPanel, /disabled=\{!hasInviteCode\}/i);
  assert.match(registerPanel, /Open signup from a valid invite link before creating an account/i);
  assert.match(registerPanel, /Invite prepared for \{inviteRecipientLabel\}/i);
});

test('training plan page uses the latest decisive monthly-planner framing and layout', async () => {
  const [planPageSource, source, calendarSource, repairPanelSource, calendarStyles, calendarPageSource, statefulBuilderSource, planRacesPageSource] = await Promise.all([
    readFile(planPagePath, 'utf8'),
    readFile(trainingPlanPagePath, 'utf8'),
    readFile(trainingPlanCalendarPath, 'utf8'),
    readFile(currentWeekRepairPanelClientPath, 'utf8'),
    readFile(calendarStylesPath, 'utf8'),
    readFile(calendarPagePath, 'utf8'),
    readFile(join(webRoot, 'app/app/_components/training-plan-stateful-builder-client.tsx'), 'utf8'),
    readFile(join(webRoot, 'app/app/plan/races/page.tsx'), 'utf8'),
  ]);

  assert.match(planPageSource, /mode=\"plan\"/i);
  assert.match(calendarPageSource, /mode=\"calendar\"/i);
  assert.match(source, /What should actually happen/i);
  assert.match(source, /Focus/i);
  assert.match(source, /Month direction/i);
  assert.match(source, /Future draft/i);
  assert.match(source, /contextPayload\.statusQuo/i);
  assert.match(source, /Recent focus/i);
  assert.doesNotMatch(source, /Upcoming races/i);
  assert.doesNotMatch(source, /<h3>Status quo<\/h3>/i);
  assert.doesNotMatch(source, /Main implication/i);
  assert.doesNotMatch(source, /Event proximity/i);
  assert.doesNotMatch(source, /Evidence window/i);
  assert.doesNotMatch(source, /Excluded by filters/i);

  assert.match(source, /nextEvent = planEvents\[0\] \|\| null/i);
  assert.match(source, /Add race or event/i);
  assert.match(source, /Add event/i);
  assert.match(source, /Edit events/i);
  assert.match(source, /training-plan-focus-event-card/i);
  assert.match(source, /training-plan-inline-panel-event/i);
  assert.match(source, /training-plan-inline-event-form/i);
  assert.match(source, /name=\"action\" value=\"update\"/i);
  assert.match(source, /name=\"action\" value=\"remove\"/i);
  assert.match(source, /Save event/i);
  assert.match(source, /Remove/i);
  assert.match(source, /name=\"returnTo\" value=\{appRoutes\.plan\}/i);
  assert.match(source, /planEventTypeLabel/i);
  assert.match(source, /Event flow/i);
  assert.match(planRacesPageSource, /<form/i);
  assert.match(planRacesPageSource, /title=\"Events\"/i);
  assert.match(planRacesPageSource, /Add the next race fast, then refine event details only when the month needs it\./i);
  assert.match(planRacesPageSource, /<h2>Events<\/h2>/i);
  assert.match(planRacesPageSource, /Track meeting Zurich/i);
  assert.match(planRacesPageSource, /name=\"date\"/i);
  assert.match(planRacesPageSource, /name=\"durationHours\"/i);
  assert.match(planRacesPageSource, /name=\"type\"/i);
  assert.match(planRacesPageSource, /name=\"priority\"/i);
  assert.match(planRacesPageSource, /\/api\/planner\/month\/events/i);
  assert.doesNotMatch(source, /training-plan-step-card/i);
  assert.doesNotMatch(source, /training-plan-step-card-status/i);
  assert.doesNotMatch(source, /training-plan-step-card-goals/i);
  assert.doesNotMatch(source, /training-plan-step-card-parameters/i);
  assert.doesNotMatch(source, /training-plan-step-card-draft/i);
  assert.doesNotMatch(source, /Go to style guide/i);
  assert.doesNotMatch(source, /Open race calendar/i);
  assert.match(statefulBuilderSource, /Generate draft/i);
  assert.doesNotMatch(source, /appRoutes\.styleGuide/i);
  assert.match(source, /Race calendar/i);
  assert.match(calendarPageSource, /mode=\"calendar\"/i);
  assert.match(source, /heroTitle = isCalendarMode \? 'Calendar' : 'Plan'/i);
  assert.match(source, /Live week first\. Future weeks stay editable\./i);
  assert.match(source, /heroTitle = isCalendarMode \? 'Calendar' : 'Plan'/i);
  assert.match(source, /training-plan-stateful-builder-client/i);
  assert.match(source, /<TrainingPlanStatefulBuilderClient/i);
  assert.match(source, /Build and review/i);
  assert.match(source, /getActivePlanningContext/i);
  assert.match(source, /Planned today/i);
  assert.match(source, /Planned tomorrow/i);
  assert.match(source, /What should actually happen/i);
  assert.doesNotMatch(source, /<strong>Live now<\/strong>/i);
  assert.doesNotMatch(source, /<strong>Tomorrow<\/strong>/i);
  assert.doesNotMatch(source, /<strong>Key slot<\/strong>/i);
  assert.match(source, /formatLiveSyncStamp/i);
  assert.match(source, /Last updated .* UTC|Snapshot refresh pending/i);
  assert.match(source, /training-plan-range-headline/i);
  assert.match(source, /formatRange/i);
  assert.match(source, /training-plan-compare-panel/i);
  assert.match(source, /training-plan-stateful-builder-client/i);
  assert.match(statefulBuilderSource, /Month direction/i);
  assert.match(source, /Live week first\. Future weeks stay editable\./i);
  assert.doesNotMatch(source, /Live week on top, editable month underneath\./i);
  assert.match(statefulBuilderSource, /Generate draft/i);
  assert.match(await readFile(join(webRoot, 'app/api/planner/month/draft/route.ts'), 'utf8'), /appRoutes\.plan\?notice=.*Draft generated|revalidatePath\(appRoutes\.calendar\)/i);
  assert.doesNotMatch(source, /Open full calendar/i);
  assert.match(source, /Generated month/i);
  assert.doesNotMatch(source, /What should actually happen this week/i);
  assert.match(source, /currentWeekReplan/i);
  assert.doesNotMatch(source, /remainingWeekHours/i);
  assert.doesNotMatch(source, /remainingQualityBudget/i);
  assert.doesNotMatch(source, /activePlanning\.todayDecision\?\.confidence/i);
  assert.match(source, /activePlanning\.todayDecision\?\.reasonSummary/i);
  assert.match(source, /activePlanning\.todayDecision\?\.decisionBasis\?\.weeklyBalance/i);
  assert.match(source, /activePlanning\.todayDecision\?\.risks/i);
  assert.match(source, /training-plan-current-week-panel__trace/i);
  assert.doesNotMatch(source, /training-plan-current-week-panel-premium/i);
  assert.match(source, /training-plan-current-week-panel__anchor-grid/i);
  assert.match(source, /training-plan-current-week-panel__anchor-tile/i);
  assert.match(source, /training-plan-current-week-panel__meta-grid/i);
  assert.match(source, /training-plan-current-week-panel__meta-tile/i);
  assert.doesNotMatch(source, /training-plan-current-week-panel__summary-callout/i);
  assert.match(source, /training-plan-current-week-panel__support-card/i);
  assert.match(source, /training-plan-mini-fact-warning/i);
  assert.match(source, /No immediate runtime risk flags\./i);
  assert.match(source, /latestRuntimeRepair/i);
  assert.match(source, /latestRuntimeRepairTarget/i);
  assert.match(source, /Latest runtime repair/i);
  assert.match(source, /Target planned slot:/i);
  assert.match(source, /training-plan-current-week-panel__latest-repair/i);
  assert.doesNotMatch(source, /Week reconciliation/i);
  assert.doesNotMatch(source, /Runtime bridge/i);
  assert.doesNotMatch(source, /builderAnalysisCards/i);
  assert.doesNotMatch(source, /Planning snapshot/i);
  assert.doesNotMatch(source, /Strengths/i);
  assert.doesNotMatch(source, /Limiters/i);
  assert.doesNotMatch(source, /Goal direction/i);
  assert.doesNotMatch(source, /Adaptation state/i);
  assert.match(source, /plannerWorkspaceCards/i);
  assert.match(source, /training-plan-workspace-shell/i);
  assert.match(source, /training-plan-workspace-rail/i);
  assert.match(source, /training-plan-workspace-main/i);
  assert.match(source, /training-plan-workspace-compact-grid/i);
  assert.match(source, /Current-week summary/i);
  assert.match(source, /Month workspace/i);
  assert.match(source, /Build and review/i);
  assert.match(source, /Today check/i);
  assert.match(source, /Month details/i);
  assert.match(source, /Draft in a nutshell/i);
  assert.doesNotMatch(source, /training-plan-category-grid/i);
  assert.doesNotMatch(source, /training-plan-intent-compare-card/i);
  assert.doesNotMatch(statefulBuilderSource, /<span>Recommended<\/span>/i);
  assert.doesNotMatch(statefulBuilderSource, /<strong>Why<\/strong>/i);
  assert.doesNotMatch(statefulBuilderSource, /<strong>Evidence<\/strong>/i);
  assert.doesNotMatch(source, /Builder, publish, analysis/i);
  assert.match(source, /training-plan-publish-panel/i);
  assert.match(source, /training-plan-builder-panel/i);
  assert.match(source, /training-plan-analysis-panel/i);
  assert.match(source, /training-plan-builder-panel-premium/i);
  assert.doesNotMatch(source, /training-plan-live-strip-premium/i);
  assert.doesNotMatch(source, /training-plan-step-card-status/i);
  assert.doesNotMatch(source, /training-plan-step-card-goals/i);
  assert.doesNotMatch(source, /training-plan-step-card-parameters/i);
  assert.doesNotMatch(source, /training-plan-step-card-draft/i);
  assert.match(source, /CurrentWeekRepairPanelClient/i);
  assert.match(source, /Today check/i);
  assert.match(source, /<summary>Today check<\/summary>/i);
  assert.doesNotMatch(source, /Week reconciliation/i);
  assert.doesNotMatch(source, /Runtime bridge/i);
  assert.doesNotMatch(source, /<div className=\"kicker\">Current week<\/div>/i);
  assert.doesNotMatch(source, /<strong>What should actually happen this week<\/strong>/i);
  assert.doesNotMatch(source, /<strong>Direction<\/strong>/i);
  assert.doesNotMatch(source, /<strong>Saved<\/strong>|<strong>Unsaved changes<\/strong>/i);
  assert.doesNotMatch(source, /<strong>Active constraints<\/strong>/i);
  assert.match(source, /initialPreviews=\{currentWeekReplan\.scenarioPreviews/i);
  assert.match(repairPanelSource, /'use client';/i);
  assert.match(repairPanelSource, /fetch\('\/api\/planner\/month\/replan'/i);
  assert.match(repairPanelSource, /intent: 'preview'/i);
  assert.match(repairPanelSource, /intent: 'apply'/i);
  assert.match(repairPanelSource, /Refresh preview/i);
  assert.match(repairPanelSource, /router\.refresh\(\)/i);
  assert.match(repairPanelSource, /Preview exact week changes/i);
  assert.match(repairPanelSource, /training-plan-current-week-panel__scenario-list/i);
  assert.match(repairPanelSource, /training-plan-current-week-panel__scenario-card/i);
  assert.match(repairPanelSource, /training-plan-current-week-panel__change-row/i);
  assert.match(repairPanelSource, /Before structure:/i);
  assert.match(repairPanelSource, /After structure:/i);
  assert.match(repairPanelSource, /Before intent:/i);
  assert.match(repairPanelSource, /After intent:/i);
  assert.match(repairPanelSource, /Why this family:/i);
  assert.match(repairPanelSource, /Protected key day:/i);
  assert.match(repairPanelSource, /<strong>Today<\/strong>/i);
  assert.match(repairPanelSource, /<strong>Tomorrow<\/strong>/i);
  assert.match(repairPanelSource, /Key slot protection/i);
  assert.match(repairPanelSource, /preview\.todayConsequence/i);
  assert.match(repairPanelSource, /preview\.tomorrowConsequence/i);
  assert.match(repairPanelSource, /preview\.keyProtectionSummary/i);
  assert.match(repairPanelSource, /previews\.map/i);
  assert.match(repairPanelSource, /\/api\/planner\/month\/replan/i);
  assert.match(repairPanelSource, /preview\.actionLabel/i);
  assert.match(repairPanelSource, /preview\.scenario/i);
  assert.match(repairPanelSource, /liveSnapshotDate/i);
  assert.match(repairPanelSource, /Reviewed live snapshot/i);
  assert.match(calendarSource, /const WORKOUT_ACTIONS = \['move_day', 'remove'\] as const;/i);
  assert.match(calendarSource, /const QUICK_WORKOUT_ACTIONS = \['skip', 'replace_with_support', 'mark_done_modified'\] as const;/i);
  assert.match(calendarSource, /training-plan-session-card__quick-actions/i);
  assert.match(calendarSource, /training-plan-session-card__quick-action/i);
  assert.match(calendarSource, /training-plan-session-card__quick-action-active/i);
  assert.match(calendarSource, /training-plan-session-card__quick-action-disabled/i);
  assert.match(calendarSource, /quickActionLabel/i);
  assert.match(calendarSource, /training-plan-week-summary-column__eyebrow/i);
  assert.match(calendarSource, /training-plan-week-summary-card__stats/i);
  assert.match(calendarSource, /training-plan-week-summary-card__stat/i);
  assert.match(calendarSource, /training-plan-week-summary-card__intent/i);
  assert.match(calendarSource, /training-plan-week-summary-card__actions/i);
  assert.match(calendarSource, /WEEK_ACTIONS: WeekAction\[] = \['regenerate', 'reduce_load', 'increase_specificity'\]/i);
  assert.match(calendarSource, /training-plan-week-summary-preview/i);
  assert.match(calendarSource, /weekView \? 'Current week focus' : 'Month overview'/i);
  assert.match(repairPanelSource, /initialDraftRevision/i);
  assert.match(repairPanelSource, /previewMetaByScenario/i);
  assert.match(repairPanelSource, /expectedDraftRevision: previewMeta\.draftRevision/i);
  assert.match(repairPanelSource, /previewToken: previewMeta\.previewToken/i);
  assert.match(repairPanelSource, /Refresh preview first/i);
  assert.match(repairPanelSource, /previewToken\.endsWith\(':initial'\)/i);
  assert.match(source, /initialDraftRevision=\{latestDraft\.revision \|\| 0\}/i);
  assert.match(calendarSource, /draftRevision: number/i);
  assert.match(calendarSource, /const \[currentDraftRevision, setCurrentDraftRevision\] = useState\(draftRevision\)/i);
  assert.match(calendarSource, /expectedDraftRevision: currentDraftRevision/i);
  assert.match(calendarSource, /setCurrentDraftRevision\(payload\.draftRevision\)/i);
  assert.match(calendarSource, /weekPreviewMetaByWeekId/i);
  assert.match(calendarSource, /expectedDraftRevision: previewMeta\.draftRevision/i);
  assert.match(calendarSource, /previewToken: previewMeta\.previewToken/i);
  assert.match(calendarSource, /Week preview is stale\. Refresh the preview before applying\.|Refresh preview first/i);
  assert.match(calendarSource, /Workout mutation is stale\. Refresh the planner before applying another change\./i);
  assert.match(source, /draftRevision=\{latestDraft\.revision \|\| 0\}/i);
  assert.match(source, /button-secondary button-link/i);
  assert.doesNotMatch(source, /Use freshness/i);
  assert.doesNotMatch(source, /Cut load/i);
  assert.match(source, /training-plan-mini-fact/i);
  assert.match(source, /training-plan-inline-panel|Publish future draft/i);
  assert.match(source, /Publish future draft/i);
  assert.match(source, /Live week stays runtime-backed/i);
  assert.match(source, /publishStateLabel/i);
  assert.match(source, /Publish state/i);
  assert.match(source, /Future weeks published locally/i);
  assert.match(source, /Runtime week stays live/i);
  assert.match(source, /Externally synced/i);
  assert.doesNotMatch(source, /training-plan-publish-inline/i);
  assert.match(calendarSource, /effectAllowed = 'move'/i);
  assert.match(calendarSource, /setData\('text\/plain', workoutIdentity\)/i);
  assert.match(calendarSource, /getData\('text\/plain'\)/i);
  assert.match(calendarSource, /<span\s+draggable\s+className=\"training-plan-session-card__drag-handle\"/i);
  assert.doesNotMatch(calendarSource, /<div\s+key=\{workout\.id\}\s+draggable=\{!workout\.locked\}/i);
  assert.match(calendarSource, /training-plan-session-card__drag-handle/i);
  assert.match(calendarSource, /training-plan-session-card__quick-actions/i);
  assert.match(calendarSource, /training-plan-session-card__quick-action/i);
  assert.match(source, /Publish future draft/i);
  assert.match(calendarSource, /past/i);
  assert.match(calendarSource, /plannedForDisplay/i);
  assert.match(calendarSource, /training-plan-day-card__summary/i);
  assert.match(calendarSource, /planEvents/i);
  assert.match(calendarSource, /durationHours/i);
  assert.match(calendarSource, /planner-race-badge/i);
  assert.match(calendarSource, /planEventBadgeClass/i);
  assert.match(calendarSource, /intervalLabel/i);
  assert.match(calendarSource, /familyIntent/i);
  assert.match(calendarSource, /selectionRationale/i);
  assert.match(calendarSource, /reconciliationEvents/i);
  assert.match(calendarSource, /reconciliationEventByWorkoutId/i);
  assert.match(calendarSource, /reconciliationEventsByWorkoutKey/i);
  assert.doesNotMatch(calendarSource, /training-plan-session-card__change-trace/i);
  assert.doesNotMatch(calendarSource, /training-plan-session-card__change-trace-title/i);
  assert.doesNotMatch(calendarSource, /Before → after/i);
  assert.match(calendarSource, /slotDiffSummary/i);
  assert.match(calendarSource, /training-plan-month-grid-compact/i);
  assert.match(calendarSource, /training-plan-month-grid-premium/i);
  assert.match(calendarSource, /training-plan-workspace-calendar-shell/i);
  assert.match(calendarSource, /training-plan-workspace-calendar-header/i);
  assert.match(calendarSource, /training-plan-workspace-week-rail/i);
  assert.match(calendarSource, /reconciliationAuditLabel\(workout, reconciliationAudit\)/i);
  assert.match(calendarSource, /workout\.matchedPlannedWorkoutLabel/i);
  assert.match(calendarSource, /workout\.completedLabel/i);
  assert.match(calendarSource, /reconciliationEvents/i);
  assert.doesNotMatch(calendarSource, /training-plan-session-card__subhead-audit/i);
  assert.match(calendarSource, /training-plan-day-card__events|planner-race-badge/i);
  assert.match(calendarSource, /training-plan-day-card-empty/i);
  assert.doesNotMatch(calendarSource, /<span className=\"training-plan-session-card__tag training-plan-session-card__tag-family\"/i);
  assert.doesNotMatch(calendarSource, /<span className=\"training-plan-session-card__tag\">\{shortCategoryLabel\(workout\.category\)\}<\/span>/i);
  assert.match(source, /recentWindow/i);
  assert.doesNotMatch(source, /compareIntentLabel/i);
  assert.doesNotMatch(source, /training-plan-intent-compare-card/i);
  assert.doesNotMatch(source, /Race-specific intent|Repeatability intent|Threshold intent/i);
  assert.doesNotMatch(source, /training-plan-review-meta/i);
  assert.doesNotMatch(source, /Live week on top, editable month underneath\./i);
  const plannerDataSource = await readFile(join(webRoot, 'lib/server/planner-data.ts'), 'utf8');
  assert.match(source, /displayedWeeks/i);
  assert.match(source, /replaceCurrentWeekWithRuntime/i);
  assert.match(plannerDataSource, /activePlanningIntentFromCycle/i);
  assert.match(plannerDataSource, /enqueueIntervalsRefreshIfStale/i);
  assert.match(plannerDataSource, /Planner live refresh queued/i);
  assert.match(plannerDataSource, /Repair the live week|Back off but keep the week coherent|Sharpen the next key slot/i);
  assert.match(plannerDataSource, /runtimeWorkoutCategory/i);
  assert.match(plannerDataSource, /weekSpanFromDraftWeek/i);
  assert.match(plannerDataSource, /weekWindowForToday/i);
  assert.match(plannerDataSource, /day\.date >= today/i);
  assert.match(plannerDataSource, /visibleWeekWorkouts/i);
  assert.match(calendarSource, /completedThisWeek/i);
  assert.match(calendarSource, /rest-day-subtle/i);
  assert.match(calendarSource, /weekSummaryLabel/i);
  assert.match(calendarSource, /week\.weekTypeLabel/i);
  assert.match(calendarSource, /week\.availableHours/i);
  assert.match(calendarSource, /week\.eventHours/i);
  assert.match(calendarSource, /availableHoursLabel/i);
  assert.match(calendarSource, /eventAdjustedHoursLabel/i);
  assert.match(calendarSource, /weekVolumeLabel/i);
  assert.doesNotMatch(calendarSource, /weekSessionCountLabel/i);
  assert.doesNotMatch(calendarSource, /Completed • \{completedCount\}/i);
  assert.doesNotMatch(calendarSource, /Planned • \{plannedCount\}/i);
  assert.doesNotMatch(calendarSource, /History: \$\{latestHistory\.label\}/i);
  assert.doesNotMatch(calendarSource, /Next \$\{\(plannedMinutes \/ 60\)\.toFixed\(1\)\} h/i);
  assert.match(calendarSource, /after .* h events/i);
  assert.match(calendarSource, /h available/i);
  assert.match(calendarSource, /weekView/i);
  assert.match(calendarSource, /setWeekView/i);
  assert.match(calendarSource, /Current week view/i);
  assert.match(calendarSource, /Full month view/i);
  assert.match(calendarSource, /calendarRowsToRender/i);
  assert.match(calendarSource, /weekRowsToRender/i);
  assert.match(calendarSource, /const workoutIdentity = workout\.plannerSlotId \|\| workout\.id/i);
  assert.match(calendarSource, /setDraggingWorkoutId\(workoutIdentity\)/i);
  assert.match(calendarSource, /setData\('text\/plain', workoutIdentity\)/i);
  assert.match(calendarSource, /training-plan-week-summary-column/i);
  assert.match(calendarSource, /training-plan-week-summary-card/i);
  assert.match(calendarSource, /calendarRows/i);
  assert.match(calendarSource, /rowIndexByWeekIndex/i);
  assert.match(calendarStyles, /--calendar-row-height:\s*clamp\(138px, 16vw, 176px\)/i);
  assert.match(calendarStyles, /\.training-plan-live-strip-premium \{[^}]*gap:\s*10px/i);
  assert.match(calendarStyles, /\.training-plan-builder-panel-premium \{[^}]*box-shadow:/i);
  assert.match(calendarStyles, /\.training-plan-current-week-panel-premium \{[^}]*box-shadow:/i);
  assert.match(calendarStyles, /\.training-plan-current-week-panel__anchor-grid,\s*\.training-plan-current-week-panel__meta-grid \{[^}]*grid-template-columns:\s*repeat\(auto-fit, minmax\(160px, 1fr\)\)/is);
  assert.match(calendarStyles, /\.training-plan-current-week-panel__anchor-tile,\s*\.training-plan-current-week-panel__meta-tile \{[^}]*border-radius:\s*16px/is);
  assert.match(calendarStyles, /\.training-plan-current-week-panel__anchor-tile-primary \{[^}]*grid-column:\s*span 2/is);
  assert.match(calendarStyles, /\.training-plan-current-week-panel__summary-callout \{[^}]*border-left:\s*3px solid rgba\(122,167,255,0\.32\)/i);
  assert.match(calendarStyles, /\.training-plan-current-week-panel__support-card \{[^}]*box-shadow:\s*inset 0 1px 0 rgba\(255,255,255,0\.02\)/i);
  assert.match(calendarStyles, /\.button-primary-premium \{[^}]*box-shadow:/i);
  assert.match(calendarStyles, /\.button-secondary-premium \{[^}]*background:\s*linear-gradient/i);
  assert.match(calendarStyles, /\.input-premium \{[^}]*box-shadow:\s*inset 0 1px 0 rgba\(255,255,255,0\.035\)/i);
  assert.match(calendarStyles, /\.auth-login-card-premium \{[^}]*box-shadow:/i);
  assert.match(calendarStyles, /\.auth-login-form-premium \{[^}]*gap:\s*18px/i);
  assert.match(calendarStyles, /\.training-plan-builder-bar-compact \{[^}]*grid-template-columns:\s*minmax\(220px, 1\.4fr\) minmax\(110px, \.56fr\) minmax\(130px, \.68fr\) auto/i);
  assert.match(calendarStyles, /\.training-plan-quick-note-emphasis \{[^}]*border-color:\s*rgba\(122,167,255,0\.18\)/i);
  assert.match(calendarStyles, /\.training-plan-month-grid-premium \{[^}]*gap:\s*14px/i);
  assert.match(calendarStyles, /\.training-plan-day-card-premium \{[^}]*backdrop-filter:\s*blur\(14px\)/i);
  assert.match(calendarStyles, /\.training-plan-session-card-premium \{[^}]*box-shadow:/i);
  assert.match(calendarStyles, /\.training-plan-week-summary-card-premium \{[^}]*box-shadow:/i);
  assert.match(calendarStyles, /\.training-plan-live-strip__item-value \{[^}]*font-size:\s*13px/i);
  assert.match(calendarStyles, /\.training-plan-live-strip__item-meta \{[^}]*font-size:\s*10px/i);
  assert.match(calendarStyles, /\.training-plan-month-grid \{[^}]*grid-auto-rows:\s*var\(--calendar-row-height\)/i);
  assert.doesNotMatch(calendarStyles, /\.training-plan-week-summary-card \{[^}]*height:\s*var\(--calendar-row-height\)/i);
  assert.match(calendarStyles, /\.training-plan-week-summary-card \{[^}]*height:\s*auto/i);
  assert.match(calendarStyles, /\.training-plan-week-summary-column \{[^}]*grid-auto-rows:\s*minmax\(0, auto\)/i);
  assert.match(calendarStyles, /\.rest-day-subtle \{[^}]*background:\s*linear-gradient\(180deg, rgba\(12,15,21,0\.74\), rgba\(10,13,19,0\.62\)\)/i);
  assert.match(calendarStyles, /\.rest-day-subtle \{[^}]*border-color:\s*rgba\(120,134,156,0\.06\)/i);
  assert.match(calendarStyles, /\.rest-day-subtle \.training-plan-day-card__header strong \{[^}]*color:\s*#d7e2f0/i);
  assert.match(calendarStyles, /\.rest-day-subtle \.training-plan-day-card__summary \{[^}]*color:\s*#9aa9bb/i);
  assert.match(calendarStyles, /\.training-plan-workspace-compact-grid,\s*\.training-plan-builder-bar-compact,\s*\.training-plan-quick-notes,\s*\.training-plan-live-strip \{[^}]*grid-template-columns:\s*1fr/i);
  assert.match(calendarStyles, /\.session-tone-rest \{[^}]*--session-border:\s*rgba\(120,134,156,0\.18\)[^}]*--session-bg:\s*rgba\(120,134,156,0\.06\)/i);
  assert.match(calendarStyles, /\.session-tone-rest \.training-plan-session-card__label \{[^}]*color:\s*#d7e2f0/i);
  assert.match(calendarStyles, /\.session-tone-rest \.training-plan-session-card__subhead \{[^}]*color:\s*#9aa9bb/i);
  assert.match(calendarStyles, /\.session-tone-rest \.training-plan-session-card__tag \{[^}]*background:\s*rgba\(255,255,255,0\.04\)[^}]*color:\s*#cbd5e1/i);
  assert.match(source, /Action/i);
  assert.match(calendarSource, /summary title=\"Session actions\"/i);
  assert.doesNotMatch(calendarSource, /case 'lock':/i);
  assert.doesNotMatch(calendarSource, /case 'easier':/i);
  assert.doesNotMatch(calendarSource, /case 'harder':/i);
  assert.doesNotMatch(calendarSource, /action: 'lock'/i);
  assert.doesNotMatch(calendarSource, /action: 'easier'/i);
  assert.doesNotMatch(calendarSource, /action: 'harder'/i);
  assert.match(source, /buildTodayReconciliationPayload/i);
  assert.match(source, /plannedVsDoneMismatch/i);
  assert.match(calendarSource, /training-plan-day-card__header/i);
  assert.match(calendarSource, /shortDateLabel/i);
  assert.match(calendarSource, /sessionToneClass/i);
  assert.match(calendarSource, /training-plan-month-grid/i);
  assert.match(calendarSource, /useEffect\(\(\) => \{\s*setWeeks\(initialWeeks\);/i);
  assert.match(calendarSource, /const \[weeks, setWeeks\] = useState<Week\[\]>\(initialWeeks\)/i);
  assert.match(calendarSource, /if \(payload\?\.weeks\) setWeeks\(payload\.weeks as Week\[\]\)/i);
  assert.match(calendarSource, /if \(payload\?\.draft\?\.weeks\) setWeeks\(payload\.draft\.weeks as Week\[\]\)/i);
  assert.doesNotMatch(calendarSource, /router\.refresh\(\)/i);
  assert.match(calendarSource, /training-plan-inline-menu/i);
  assert.match(calendarSource, /training-plan-session-card__quick-actions/i);
  assert.match(calendarSource, /quickActionLabel/i);
  assert.match(calendarSource, /quickActionDisabled/i);
  assert.match(calendarSource, /mutateWorkout\(workout\.id, 'reset_reconciliation'\)/i);
  assert.match(calendarSource, /training-plan-session-card__drag-handle/i);
  assert.match(calendarSource, /Drag to move this session/i);
  assert.doesNotMatch(calendarSource, /mutateWorkout\(workout\.id, 'easier'\)/i);
  assert.doesNotMatch(calendarSource, /mutateWorkout\(workout\.id, 'remove'\)/i);
  assert.match(calendarSource, /training-plan-inline-menu__action-list/i);
  assert.match(calendarSource, /training-plan-inline-menu__action-pill/i);
  assert.match(calendarSource, /training-plan-inline-menu__action-pill-active/i);
  assert.match(calendarSource, /type=\"button\"/i);
  assert.match(calendarSource, /setMenuActionByWorkout\(\(current\) => \(\{/i);
  assert.match(calendarSource, /disabled=\{actionDisabled\}/i);
  assert.match(calendarSource, /normalizeWorkoutAction\(workout, menuActionByWorkout\[workout\.id\] \|\| 'move_day'\)/i);
  assert.doesNotMatch(calendarSource, /option value=\"replace_with_support\"/i);
  assert.doesNotMatch(calendarSource, /option value=\"mark_done_modified\"/i);
  assert.doesNotMatch(calendarSource, /option value=\"remove\"/i);
  assert.match(calendarSource, /<input type=\"hidden\" name=\"action\" value=\{selectedAction\}/i);
  assert.doesNotMatch(calendarSource, /<select/i);
  assert.doesNotMatch(calendarSource, /training-plan-inline-menu__selected-action-row/i);
  assert.doesNotMatch(calendarSource, /training-plan-inline-menu__selected-action-label/i);
  assert.doesNotMatch(calendarSource, /option value=\"harder\"/i);
  assert.doesNotMatch(calendarSource, /option value=\"lock\"/i);
  assert.doesNotMatch(calendarSource, /Remove now/i);
  assert.match(calendarSource, /dayHint\(draggingWorkoutId, date\)/i);
  assert.doesNotMatch(calendarSource, /Same-day conflict/i);
  assert.match(calendarSource, /Back-to-back hard risk/i);
  assert.match(calendarSource, /Drop looks usable/i);
  assert.match(calendarSource, /training-plan-day-card__drop-hint/i);
  assert.match(calendarStyles, /training-plan-session-card__drag-handle/i);
  assert.match(calendarStyles, /cursor:\s*grab/i);
  assert.match(calendarStyles, /training-plan-session-card-status-skipped/i);
  assert.match(calendarStyles, /training-plan-session-card-status-replaced/i);
  assert.match(calendarStyles, /training-plan-session-card-status-completed-modified/i);
  assert.match(calendarStyles, /training-plan-session-card__inline-feedback/i);
  assert.match(calendarStyles, /training-plan-session-card__quick-actions/i);
  assert.match(calendarStyles, /training-plan-session-card__quick-action-disabled/i);
  assert.match(calendarStyles, /training-plan-session-card__quick-action-active/i);
  assert.doesNotMatch(calendarStyles, /training-plan-session-card__quick-action-undo/i);
  assert.doesNotMatch(calendarStyles, /training-plan-day-card-drop-blocked/i);
  assert.doesNotMatch(calendarStyles, /training-plan-day-card__drop-hint-blocked/i);
  assert.doesNotMatch(calendarStyles, /training-plan-inline-menu__select-danger/i);
  assert.match(calendarStyles, /training-plan-inline-menu__action-list/i);
  assert.match(calendarStyles, /training-plan-inline-menu__action-pill/i);
  assert.match(calendarStyles, /training-plan-inline-menu__action-pill-active/i);
  assert.match(calendarStyles, /training-plan-inline-menu__submit-danger/i);
  assert.match(calendarStyles, /training-plan-inline-menu__danger-hint/i);
  assert.match(calendarStyles, /training-plan-inline-menu__action-hint/i);
  assert.match(calendarStyles, /training-plan-inline-panel-event/i);
  assert.match(calendarStyles, /training-plan-focus-event-card/i);
  assert.match(calendarStyles, /training-plan-inline-event-form/i);
  assert.doesNotMatch(calendarStyles, /training-plan-inline-menu__selected-action-row/i);
  assert.match(calendarStyles, /training-plan-inline-menu__panel-title/i);
  assert.match(calendarStyles, /training-plan-inline-menu__panel-copy/i);
  assert.match(calendarStyles, /training-plan-inline-menu__move-note/i);
  assert.match(calendarStyles, /training-plan-current-week-panel/i);
  assert.match(calendarStyles, /training-plan-session-card__tag-family/i);
  assert.match(calendarStyles, /training-plan-intent-compare-card__kicker/i);
  assert.match(calendarStyles, /letter-spacing:\s*-0\.12em/i);
  assert.match(calendarStyles, /training-plan-day-card-drop-warning/i);

  assert.doesNotMatch(calendarStyles, /training-plan-day-card-drop-blocked/i);
  assert.match(calendarSource, /Move day/i);
  assert.match(calendarSource, /showMoveDateField/i);
  assert.match(calendarSource, /menuActionByWorkout/i);
  assert.match(calendarSource, /actionSubmitLabel/i);
  assert.match(calendarSource, /actionSelectionLabel/i);
  assert.match(calendarSource, /shouldCloseMenuAfterSubmit/i);
  assert.match(calendarSource, /closeMenuAfterSubmit/i);
  assert.match(calendarSource, /destructiveActionSelected/i);
  assert.match(calendarSource, /training-plan-inline-menu__action-list/i);
  assert.match(calendarSource, /training-plan-inline-menu__action-pill/i);
  assert.match(calendarSource, /training-plan-inline-menu__action-pill-active/i);
  assert.match(calendarSource, /training-plan-inline-menu__action-pill-danger/i);
  assert.match(calendarSource, /training-plan-inline-menu__submit-danger/i);
  assert.match(calendarSource, /training-plan-inline-menu__danger-hint/i);
  assert.match(calendarSource, /training-plan-inline-menu__action-hint/i);
  assert.match(calendarSource, /actionConsequenceHint/i);
  assert.match(calendarSource, /actionSuccessNotice/i);
  assert.doesNotMatch(calendarSource, /training-plan-inline-menu__selected-action-label/i);
  assert.match(calendarSource, /training-plan-inline-menu__panel-title/i);
  assert.match(calendarSource, /training-plan-inline-menu__panel-copy/i);
  assert.match(calendarSource, /training-plan-inline-menu__action-summary/i);
  assert.match(calendarSource, /training-plan-inline-menu__move-note/i);
  assert.match(calendarSource, /Select the reconciliation path, then confirm\./i);
  assert.match(calendarSource, /Pick the day that best preserves freshness and key intent\./i);
  assert.match(calendarSource, /This keeps the day on the calendar but records that execution diverged\./i);
  assert.match(calendarSource, /This removes the planned session from the draft calendar\./i);
  assert.match(calendarSource, /Replaced .* with support in the draft/i);
  assert.match(calendarSource, /Marked .* done\* in the draft/i);
  assert.match(calendarSource, /Removed .* from the draft/i);
  assert.match(calendarSource, /Draft reconciled/i);
  assert.match(calendarSource, /closest\('details'\)/i);
  assert.match(calendarSource, /HTMLDetailsElement/i);
  assert.match(calendarSource, /Move to day/i);
  assert.match(calendarSource, /Mark skipped/i);
  assert.match(calendarSource, /Mark done\*/i);
  assert.match(calendarSource, /WORKOUT_ACTIONS\.map\(\(action\) => \{/i);
  assert.match(calendarSource, /aria-pressed=\{actionActive \? 'true' : 'false'\}/i);
  assert.match(calendarSource, /const WORKOUT_ACTIONS = \['move_day', 'remove'\] as const;/i);
  assert.match(calendarSource, /const QUICK_WORKOUT_ACTIONS = \['skip', 'replace_with_support', 'mark_done_modified'\] as const;/i);
  assert.match(calendarSource, /action === 'remove'/i);
  assert.match(calendarSource, /statusTagLabel/i);
  assert.match(calendarSource, /statusToneClass/i);
  assert.match(calendarSource, /isVisiblePastPlannedWorkout/i);
  assert.match(calendarSource, /Skip/i);
  assert.match(calendarSource, /Replace with support/i);
  assert.match(calendarSource, /Mark done\*/i);
  assert.match(calendarSource, /reconciliationNote/i);
  assert.match(calendarSource, /status !== 'planned'/i);
  assert.doesNotMatch(calendarSource, /Skip now/i);
  assert.doesNotMatch(calendarSource, /Replace now/i);
  assert.doesNotMatch(calendarSource, /Done\* now/i);
  assert.doesNotMatch(source, /Week controls/i);
  assert.doesNotMatch(source, /currentWeekBridge\?\.draftBridgeLabel/i);
  assert.doesNotMatch(source, /Draft built from/i);
  assert.doesNotMatch(source, /training-plan-review-guide-grid/i);

  assert.match(source, /training-plan-mini-facts/i);
  assert.match(source, /training-plan-mini-fact/i);
  assert.doesNotMatch(source, /training-plan-week-decision-grid/i);
  assert.doesNotMatch(source, /training-plan-week-decision-callout/i);
  assert.match(repairPanelSource, /preview\.actionLabel/i);
  assert.doesNotMatch(source, /Cut load/i);
  assert.doesNotMatch(source, /Use freshness/i);
  assert.match(plannerDataSource, /Race-like|Too fatigued|Repair/i);
  assert.match(source, /buildPlannerTruthSummaryPayload/i);
  assert.doesNotMatch(source, /Execution changes/i);
  assert.doesNotMatch(source, /truthSummary\.summary/i);
  assert.doesNotMatch(source, /truthSummary\.currentWeekSeverity/i);
  assert.doesNotMatch(source, /truthSummary\.currentWeekToday\.summary/i);
  assert.doesNotMatch(source, /Drift:/i);
  assert.doesNotMatch(source, /Today truth/i);
  assert.doesNotMatch(source, /truthSummary\.currentWeekSignal/i);
  assert.doesNotMatch(source, /truthSummary\.recentEvents\.map/i);
  assert.doesNotMatch(source, /truthSummary\.counters\.skipped/i);
  assert.doesNotMatch(source, /truthSummary\.counters\.replaced/i);
  assert.doesNotMatch(source, /truthSummary\.counters\.completedModified/i);
  assert.doesNotMatch(source, /truthSummary\.counters\.moved/i);
  assert.doesNotMatch(source, /truthSummary\.counters\.repaired/i);
  assert.match(calendarStyles, /training-plan-execution-changes/i);
  assert.match(calendarStyles, /training-plan-execution-changes__events/i);
  assert.match(source, /<strong>Planned today<\/strong>/i);
  assert.doesNotMatch(source, /<strong>Do today<\/strong>/i);
  assert.match(source, /<strong>Planned tomorrow<\/strong>/i);
  assert.doesNotMatch(source, /<strong>Tomorrow if today lands<\/strong>/i);
  assert.doesNotMatch(source, /<strong>Completed today<\/strong>/i);
  assert.doesNotMatch(source, /<strong>Key session protected<\/strong>/i);
  assert.doesNotMatch(source, /<strong>Done today<\/strong>/i);
  assert.match(source, /plannedVsDoneMismatch/i);
  assert.doesNotMatch(source, /Do now/i);
  assert.match(source, /Done so far/i);
  assert.match(source, /Mismatch/i);
  assert.doesNotMatch(source, /training-plan-current-week-panel__reconciliation-strip/i);
  assert.doesNotMatch(source, /training-plan-current-week-panel__reconciliation-cell/i);
  assert.doesNotMatch(source, /training-plan-current-week-panel__reconciliation-cell-mismatch/i);
  assert.match(source, /protectedKeyDayLabel/i);
  assert.match(source, /completedTodaySummary/i);
  assert.match(source, /protectionOutcome/i);
  assert.match(source, /tomorrowIfTodayLands/i);
  assert.match(source, /If today slips/i);
  assert.doesNotMatch(source, /training-plan-current-week-panel__decision-grid/i);
  assert.doesNotMatch(source, /training-plan-current-week-panel__completed-today/i);
  assert.match(source, /training-plan-current-week-panel__consequence/i);
  assert.match(repairPanelSource, /preview\.actionLabel/i);
  assert.match(repairPanelSource, /preview\.scenario/i);
  assert.doesNotMatch(source, /<button type="submit" className="button-secondary button-link">Use freshness<\/button>/i);
  assert.doesNotMatch(source, /<button type="submit" className="button-secondary button-link">Cut load<\/button>/i);
  assert.doesNotMatch(source, /<strong>Hours left<\/strong>/i);
  assert.doesNotMatch(source, /<strong>Key slots<\/strong>/i);
  assert.doesNotMatch(source, /More week actions/i);
  assert.match(plannerDataSource, /currentWeekScenarioActionLabel/i);
  assert.match(plannerDataSource, /case 'missed_session': return 'Repair'/i);
  assert.match(plannerDataSource, /case 'fatigued': return 'Too fatigued'/i);
  assert.match(plannerDataSource, /case 'increase_specificity': return 'Race-like'/i);
  assert.match(source, /Build and review/i);
  assert.doesNotMatch(source, /Builder, publish, analysis/i);
  assert.doesNotMatch(source, /Live now/i);
  assert.match(statefulBuilderSource, /Month direction/i);
  assert.match(source, /training-plan-quick-builder/i);
  assert.match(statefulBuilderSource, /training-plan-focus-chip/i);
  assert.match(statefulBuilderSource, /selectedRecommendationReason/i);
  assert.match(statefulBuilderSource, /selectedRecommendationTitle/i);
  assert.match(statefulBuilderSource, /selectedRecommendationSource/i);
  assert.match(statefulBuilderSource, /selectedRecommendationConfidence/i);
  assert.match(statefulBuilderSource, /<form action=\"\/api\/planner\/month\/draft\" method=\"post\" className=\"training-plan-stateful-builder-client\">/i);
  assert.match(statefulBuilderSource, /type=\"hidden\" name=\"objective\" value=\{submitPayload\.objective\}/i);
  assert.match(statefulBuilderSource, /name=\"objectiveVisible\" value=\{selectedFocusObjective\}/i);
  assert.match(statefulBuilderSource, /name=\"maxWeeklyHours\"[^\n]*value=\{maxWeeklyHours\}/i);
  assert.match(statefulBuilderSource, /name=\"maxWeekdayMinutes\" value=\{submitPayload\.maxWeekdayMinutes\}/i);
  assert.match(statefulBuilderSource, /name=\"unavailableDates\" value=\{date\}/i);
  assert.match(statefulBuilderSource, /name=\"restDay\" value=\{restDay\}/i);
  assert.match(statefulBuilderSource, /name=\"restDaysPerWeek\" value=\{restDaysPerWeek\}/i);
  assert.doesNotMatch(statefulBuilderSource, /<span>Month focus<\/span>[\s\S]*<select name=\"objectiveVisible\"/i);
  assert.doesNotMatch(statefulBuilderSource, /training-plan-builder-bar-compact[\s\S]*<span>Rest days \/ week<\/span>[\s\S]*Generate draft/i);
  assert.match(statefulBuilderSource, /name=\"longRideDay\" value=\{longRideDay\}/i);
  assert.match(statefulBuilderSource, /name=\"useLast28DaysOnly\" value=\"true\"/i);
  assert.match(statefulBuilderSource, /name=\"ignoreSickWeek\" value=\"true\"/i);
  assert.match(statefulBuilderSource, /name=\"ignoreVacationWeek\" value=\"true\"/i);
  assert.match(statefulBuilderSource, /name=\"excludeNonPrimarySport\" value=\"true\"/i);
  assert.match(statefulBuilderSource, /name=\"note\"[^\n]*value=\{note\}/i);
  assert.match(statefulBuilderSource, /name=\"successMarkers\" value=\{item\} checked=\{selectedSuccessMarkers\.includes\(item\)\}/i);
  assert.match(statefulBuilderSource, /type=\"button\"/i);
  assert.match(statefulBuilderSource, /aria-pressed=\{primaryChipPressed\}/i);
  assert.match(statefulBuilderSource, /aria-pressed=\{altChipPressed\(item\.objective\)\}/i);
  assert.match(statefulBuilderSource, /training-plan-focus-chip-selected/i);
  assert.match(statefulBuilderSource, /const primaryChipPressed = selectedFocusObjective === recommendationPrimary\.objective \? 'true' : 'false'/i);
  assert.match(statefulBuilderSource, /return selectedRecommendationSource === 'alternative' && selectedFocusObjective === objective \? 'true' : 'false'/i);
  assert.doesNotMatch(statefulBuilderSource, /className=\"training-plan-focus-chip-form\"/i);
  assert.match(statefulBuilderSource, /More options/i);
  assert.doesNotMatch(statefulBuilderSource, /Active constraints/i);
  assert.doesNotMatch(statefulBuilderSource, /<strong>Saved<\/strong>|<strong>Unsaved changes<\/strong>/i);
  assert.doesNotMatch(statefulBuilderSource, /<p>Draft updated<\/p>/i);
  assert.match(statefulBuilderSource, /Plan snapshot/i);
  assert.match(source, /Built from/i);
  assert.match(statefulBuilderSource, /Max hours \/ week|Maximum hours \/ week|Weekly cap|upper ceiling/i);
  assert.match(statefulBuilderSource, /parseUnavailableDatesInput/i);
  assert.match(statefulBuilderSource, /setMaxWeekdayMinutes/i);
  assert.match(statefulBuilderSource, /setUnavailableDatesInput/i);
  assert.match(statefulBuilderSource, /name=\"maxWeekdayMinutes\"[^\n]*onChange=/i);
  assert.match(statefulBuilderSource, /name=\"unavailableDatesEditor\"/i);
  assert.match(statefulBuilderSource, /name=\"useLast28DaysOnly\"[^\n]*onChange=/i);
  assert.match(statefulBuilderSource, /name=\"ignoreSickWeek\"[^\n]*onChange=/i);
  assert.match(statefulBuilderSource, /name=\"ignoreVacationWeek\"[^\n]*onChange=/i);
  assert.match(statefulBuilderSource, /name=\"excludeNonPrimarySport\"[^\n]*onChange=/i);
  assert.match(statefulBuilderSource, /Weekday cap/i);
  assert.match(statefulBuilderSource, /Unavailable dates/i);
  assert.match(statefulBuilderSource, /Data filters/i);
  assert.match(statefulBuilderSource, /Last 28 days only/i);
  assert.match(statefulBuilderSource, /Ignore sick week/i);
  assert.match(statefulBuilderSource, /Ignore vacation week/i);
  assert.match(statefulBuilderSource, /Exclude non-primary sport/i);
  assert.match(statefulBuilderSource, /Month direction/i);
  assert.match(statefulBuilderSource, /name=\"restDay\"/i);
  assert.match(statefulBuilderSource, /name=\"restDaysPerWeek\"/i);
  assert.match(statefulBuilderSource, /<span>Rest days \/ week<\/span>[\s\S]*name=\"restDaysPerWeek\"/i);
  assert.match(statefulBuilderSource, /name=\"longRideDay\"/i);
  assert.match(statefulBuilderSource, /useState\(/i);
  assert.match(statefulBuilderSource, /selectedFocusObjective/i);
  assert.match(statefulBuilderSource, /setSelectedFocusObjective/i);
  assert.match(statefulBuilderSource, /buildBuilderSubmitPayload\(builderState\)/i);
  assert.match(statefulBuilderSource, /selectAlternativeRecommendation\(builderState/i);
  assert.match(statefulBuilderSource, /selectPrimaryRecommendation\(builderState/i);
  assert.match(statefulBuilderSource, /applyManualObjectiveOverride/i);
  assert.match(statefulBuilderSource, /buildBuilderSubmitPayload/i);
  assert.match(statefulBuilderSource, /selectAlternativeRecommendation/i);
  assert.match(statefulBuilderSource, /selectPrimaryRecommendation/i);
  assert.match(statefulBuilderSource, /Generate draft/i);
  assert.match(source, /Generated month/i);
  assert.match(statefulBuilderSource, /Direction/i);
  assert.doesNotMatch(source, /Builder, publish, analysis/i);
  assert.match(statefulBuilderSource, /recommendationAlternatives\.map/i);
  assert.match(statefulBuilderSource, /training-plan-focus-chip/i);
  assert.match(statefulBuilderSource, /\{item\.title\}/i);
  assert.doesNotMatch(source, /Understand, decide, build, then review/i);
  assert.doesNotMatch(source, /Use this first/i);
  assert.doesNotMatch(source, /Live, not guessed/i);
  assert.doesNotMatch(source, /If it looks wrong/i);
  assert.doesNotMatch(source, /Accept recommendation/i);
  assert.doesNotMatch(source, /Use recommendation<\/button>/i);
  assert.doesNotMatch(source, /Why this recommendation/i);
  assert.doesNotMatch(source, /Risks to watch/i);
  assert.doesNotMatch(source, /recommendedConstraints/i);
  assert.doesNotMatch(source, /1\. Check the live week/i);
  assert.doesNotMatch(source, /2\. Adjust the draft bridge/i);
  assert.doesNotMatch(source, /3\. Tidy the month/i);
  assert.doesNotMatch(source, /Week controls/i);
  assert.doesNotMatch(source, /More week actions/i);
  assert.doesNotMatch(source, /training-plan-inline-panel-week-actions/i);
  assert.match(source, /More month actions/i);
  assert.match(calendarStyles, /--m3-radius-md/i);
  assert.match(calendarStyles, /border-radius:\s*999px/i);
  assert.match(calendarStyles, /training-plan-mini-facts/i);
  assert.match(calendarStyles, /training-plan-week-decision-grid/i);
  assert.match(calendarStyles, /training-plan-week-decision-callout/i);
  assert.match(calendarStyles, /planner-race-badge-a/i);
  assert.match(calendarStyles, /planner-race-badge-b/i);
  assert.match(calendarStyles, /planner-race-badge-c/i);
  assert.match(calendarStyles, /planner-race-badge-blackout/i);
  assert.match(calendarStyles, /training-plan-quick-builder/i);
  assert.match(calendarStyles, /training-plan-quick-builder__header/i);
  assert.match(calendarStyles, /training-plan-focus-row/i);
  assert.match(calendarStyles, /training-plan-focus-chip/i);
  assert.match(calendarStyles, /training-plan-focus-chip-selected/i);
  assert.match(calendarStyles, /\.training-plan-focus-chip\[aria-pressed='true'\]/i);
  assert.match(calendarStyles, /training-plan-builder-bar/i);
  assert.match(calendarStyles, /training-plan-builder-advanced/i);
  assert.match(calendarStyles, /training-plan-live-strip/i);
  assert.doesNotMatch(source, /training-plan-calendar-toolbar/i);
  assert.match(source, /Next key day/i);
  assert.doesNotMatch(source, /Risk:/i);
  assert.match(repairPanelSource, /\/api\/planner\/month\/replan/i);
  assert.match(calendarSource, /moveFeedback/i);
  assert.match(calendarSource, /successNotice/i);
  assert.match(calendarSource, /Move applied/i);
  assert.match(calendarSource, /Draft reconciled/i);
  assert.match(calendarSource, /Move blocked/i);
  assert.match(calendarSource, /Requested day:/i);
  assert.match(calendarSource, /Use suggested day/i);
  assert.match(calendarSource, /inlineMoveFeedback/i);
  assert.match(calendarSource, /training-plan-session-card__inline-feedback/i);
  assert.match(calendarSource, /payload\?\.code === 'move_conflict'/i);
  assert.match(source, /Use suggested day/i);
  assert.match(source, /moveConflictReason/i);
  assert.match(source, /moveConflictSuggestedDate/i);
  assert.match(source, /training-plan-stale-draft-banner/i);
  assert.match(source, /Draft is stale:/i);
  assert.match(source, /Refresh draft/i);
  assert.match(source, /staleDraftReason/i);
  assert.match(source, /draftNeedsExplicitRefresh/i);
  assert.match(source, /Review stays locked until refresh\./i);
  assert.doesNotMatch(source, /Refresh draft from latest live data/i);
  assert.match(source, /recentWindow/i);
  assert.match(source, /draftWindow/i);
  assert.doesNotMatch(source, /categoryComparison/i);
  assert.match(source, /comparePayload\.summary/i);
  assert.doesNotMatch(source, /Delta sessions:/i);
  assert.match(source, /Publish future draft/i);
  assert.match(source, /getLatestMonthlyPlanDraft/i);
  assert.match(source, /getLatestMonthlyPlanInput/i);
  assert.match(source, /staleDraftReason/i);
  assert.match(source, /latestDraft\.monthStart !== currentMonthStart/i);
  assert.match(source, /latestDraft\.updatedAt \|\| ''\)\.slice\(0, 10\) < today/i);
  assert.doesNotMatch(source, /needsAutomaticDraftRefresh/i);
  assert.doesNotMatch(source, /saveMonthlyPlanDraft/i);
  assert.doesNotMatch(source, /buildMonthlyPlannerDraftPayload/i);
  assert.match(source, /currentDirection/i);
  assert.match(await readFile(join(webRoot, 'lib/server/planner-data.ts'), 'utf8'), /goals, current figures, and recent history|current figures, and recent history/i);
  assert.doesNotMatch(source, /title="Your Goals & Plan"/i);
  assert.doesNotMatch(source, /Goal direction summary/i);
});

test('dashboard pages keep the shared page hero shell and current dashboard embed structure', async () => {
  const [pageSource, dashboardSource, liveRefreshSource, deviceLocationSyncSource, coachDashboardSource, layoutSource] = await Promise.all([
    readFile(dashboardPagePath, 'utf8'),
    readFile(dashboardScriptPath, 'utf8'),
    readFile(appLiveRefreshPath, 'utf8'),
    readFile(deviceLocationSyncPath, 'utf8'),
    readFile(join(webRoot, 'lib/server/coach-dashboard.ts'), 'utf8'),
    readFile(join(webRoot, 'app/layout.tsx'), 'utf8'),
  ]);

  assert.match(pageSource, /AppHero/i);
  assert.match(pageSource, /title="Training Dashboard"/i);
  assert.match(pageSource, /dashboard-fragment-host/i);
  assert.doesNotMatch(pageSource, /LocationRefreshButton/i);
  assert.match(layoutSource, /<AppLiveRefresh \/>/i);
  assert.match(liveRefreshSource, /REFRESH_INTERVAL_MS = 5 \* 60 \* 1000/i);
  assert.match(liveRefreshSource, /APP_REFRESH_PATHS = new Set\(\['\/app\/dashboard', '\/app\/plan', '\/app\/calendar'\]\)/i);
  assert.match(liveRefreshSource, /window\.setInterval\(refreshIfStale, REFRESH_INTERVAL_MS\)/i);
  assert.match(liveRefreshSource, /window\.addEventListener\('focus', refreshIfStale\)/i);
  assert.match(liveRefreshSource, /document\.addEventListener\('visibilitychange', handleVisibility\)/i);
  assert.match(liveRefreshSource, /const dayChanged = activeDayRef\.current !== currentDay/i);
  assert.match(liveRefreshSource, /router\.refresh\(\)/i);
  assert.match(deviceLocationSyncSource, /const staleLocation = !city \|\| city === 'current location' \|\| !hasCoords/i);
  assert.match(deviceLocationSyncSource, /maximumAge: staleLocation \? 0 : 30 \* 60 \* 1000/i);
  assert.match(deviceLocationSyncSource, /router\.refresh\(\)/i);
  assert.match(deviceLocationSyncSource, /pathname\?\.startsWith\('\/app'\)/i);
  assert.match(coachDashboardSource, /const city = cookieCity \|\|/i);
  assert.match(coachDashboardSource, /const country = cookieCity \? cookieCountry/i);
  assert.match(dashboardSource, /<div class="kicker">Overview<\/div>/i);
  assert.doesNotMatch(dashboardSource, /<div class="kicker">Training Dashboard<\/div>/i);
  assert.match(dashboardSource, /overview-grid/i);
  assert.doesNotMatch(dashboardSource, /overview-metrics/i);
  assert.doesNotMatch(dashboardSource, /overview-support/i);
  assert.match(dashboardSource, /volume-grid/i);
  assert.match(pageSource, /title="Training Dashboard"/i);
  assert.match(pageSource, /getActivePlanningContext/i);
  assert.match(pageSource, /Planning/i);
  assert.match(pageSource, /Week call/i);
  assert.match(pageSource, /Read-only analysis/i);
  assert.match(pageSource, /Power profile/i);
  assert.match(pageSource, /Block state/i);
  assert.match(pageSource, /Goal alignment/i);
  assert.match(pageSource, /Adaptation state/i);
  assert.match(pageSource, /Planned today/i);
  assert.match(pageSource, /Actually today/i);
  assert.match(pageSource, /Planned tomorrow/i);
  assert.match(pageSource, /Tomorrow likely becomes/i);
  assert.match(pageSource, /Why this is the call/i);
  assert.match(pageSource, /formatLiveSyncStamp/i);
  assert.match(pageSource, /Last updated .* UTC|Snapshot refresh pending/i);
  assert.match(dashboardSource, /<div class="overview-copy">\{esc\(live_sync_stamp\)\}<\/div>/i);
  assert.match(dashboardSource, /def format_last_updated\(value: Any\) -> str:/i);
  assert.match(dashboardSource, /merged_live_state\['last_updated_at'\] = latest\.get\('capturedAt'\)/i);
  assert.match(dashboardSource, /md-page-hero/i);
  assert.match(dashboardSource, /Today view/i);
  assert.match(dashboardSource, /Tomorrow view/i);
  assert.doesNotMatch(dashboardSource, /This week plan/i);
  assert.match(dashboardSource, /<h2>Last activity<\/h2>/i);
  assert.match(dashboardSource, /Last activity - /i);
  assert.match(dashboardSource, /Ride analysis/i);
  assert.doesNotMatch(dashboardSource, /Past take/i);
  assert.match(dashboardSource, /weather.*current location|current location.*weather|weather-place/i);
  assert.match(dashboardSource, /DEFAULT_WEATHER_LABEL = f'\{DEFAULT_WEATHER_CITY\}, \{DEFAULT_WEATHER_COUNTRY\}'/i);
  assert.match(dashboardSource, /if key == 'next_three' and isinstance\(value, list\):/i);
  assert.match(dashboardSource, /if not merged_item\.get\('weather'\):/i);
  assert.match(dashboardSource, /merged_item\['weather'\] = base_item\.get\('weather'\)/i);
  assert.match(dashboardSource, /city = DEFAULT_WEATHER_CITY/i);
  assert.match(dashboardSource, /state\['today_weather'\] = weather_by_date\.get\(state\.get\('today'\)\) or state\.get\('today_weather'\)/i);
  assert.match(dashboardSource, /derive_week_rows_from_recent_rows/i);
  assert.match(dashboardSource, /missed-row/i);
  assert.match(dashboardSource, /planned \/ not done/i);
  assert.match(dashboardSource, /Daily user input/i);
  assert.match(dashboardSource, /type="range"/i);
  assert.match(dashboardSource, /disabled/i);
  assert.match(dashboardSource, /<h2>Training plan<\/h2>/i);
  assert.match(dashboardSource, /latest-grid/i);
  assert.match(dashboardSource, /chart-top-row/i);
  assert.match(dashboardSource, /<h3>Fitness trend<\/h3>/i);
  assert.match(dashboardSource, /<h3>Current month<\/h3>/i);
  assert.match(dashboardSource, /summary-chip-row/i);
  assert.match(dashboardSource, /render_cumulative_summary\(state.get\('month_summary'\) or \{\}, 'This month'\)/i);
  assert.match(dashboardSource, /render_cumulative_summary\(state.get\('year_summary'\) or \{\}, 'This year'\)/i);
  assert.match(dashboardSource, /sessions incl\. virtual/i);
  assert.match(dashboardSource, /virtual placeholders/i);
  assert.match(dashboardSource, /month_summary/i);
  assert.match(dashboardSource, /year_summary/i);
  assert.match(dashboardSource, /<h3>This Week<\/h3>/i);
  assert.match(dashboardSource, /<h3>This Month<\/h3>/i);
  assert.match(dashboardSource, /Rest day/i);
  assert.match(dashboardSource, /timeline_rows/i);
  assert.match(dashboardSource, /activity-label/i);
  assert.match(dashboardSource, /chart-month-separator/i);
  assert.match(dashboardSource, /well\[-365:\] if well else \[\]/i);
  assert.match(dashboardSource, /wind_speed_10m_max/i);
  assert.match(dashboardSource, /resp\.raw\.headers\.get_all\('Set-Cookie'\)/i);
  assert.match(dashboardSource, /reverse_geocode_label\(latitude, longitude\)/i);
  assert.match(dashboardSource, /z5 >= 10 \* 60 or z6 >= 6 \* 60/i);
  assert.match(dashboardSource, /category_color\(session_category_from_row\(row\)\)/i);
});

test('middleware protects app pages and sends logged-out users to login by default', async () => {
  const source = await readFile(middlewarePath, 'utf8');

  assert.match(source, /pathname\.startsWith\('\/app'\)/i);
  assert.match(source, /redirectTo\(appRoutes\.login, request\)/i);
  assert.match(source, /pathname === appRoutes\.landing/i);
  assert.match(source, /matcher:/i);
});

test('configuration pages expose athlete configuration and admin-only user management subtab structure', async () => {
  const [header, account, admin, intervalsConnectPanel, syncStatusSource, syncHealthSource, inviteCreateRoute, inviteRevokeRoute] = await Promise.all([
    readFile(headerPath, 'utf8'),
    readFile(accountPagePath, 'utf8'),
    readFile(adminPagePath, 'utf8'),
    readFile(intervalsConnectPanelPath, 'utf8'),
    readFile(syncStatusPagePath, 'utf8'),
    readFile(join(webRoot, 'lib/server/sync-health.ts'), 'utf8'),
    readFile(join(webRoot, 'app/api/invites/create/route.ts'), 'utf8'),
    readFile(join(webRoot, 'app/api/invites/revoke/route.ts'), 'utf8'),
  ]);

  assert.doesNotMatch(header, /label: 'Configuration'/i);
  assert.doesNotMatch(header, /label: 'Your Goals & Plan'/i);
  assert.match(header, /label: 'Insight'/i);
  assert.match(header, /label: 'Plan'/i);
  assert.match(header, /GET DECISIVE/i);
  assert.match(header, /userDisplayName/i);
  assert.match(header, /userEmail/i);
  assert.match(header, /Config\n/i);
  assert.doesNotMatch(header, /Le ciel et la limite/i);
  assert.match(account, /title="Configuration"/i);
  assert.doesNotMatch(account, /tab === 'intervals'/i);
  assert.match(account, /Intervals connection/i);
  assert.match(account, /Display name/i);
  assert.match(account, /Athlete profile/i);
  assert.match(account, /Update password/i);
  assert.match(account, /Invites/i);
  assert.match(account, /Recipient name/i);
  assert.match(account, /Recipient email/i);
  assert.match(account, /Registration link:/i);
  assert.match(account, /Share link/i);
  assert.match(account, /Open invite link/i);
  assert.match(account, /buildInviteRegistrationUrl/i);
  assert.match(account, /tab === 'invites'/i);
  assert.match(account, /tab=\$\{entry\.id\}|id: 'invites'/i);
  assert.match(account, /table/i);
  assert.doesNotMatch(account, /<span className="chip">Email:/i);
  assert.doesNotMatch(account, /Onboarding:/i);
  assert.doesNotMatch(account, /Connection label/i);
  assert.match(account, /Athlete ID/i);
  assert.match(account, /getSyncHealthSummary/i);
  assert.match(account, /Sync health/i);
  assert.match(account, /Snapshot freshness/i);
  assert.match(account, /Last snapshot/i);
  assert.match(account, /Failure reason/i);
  assert.match(account, /Open sync status/i);
  assert.match(account, /Saving credentials here retriggers the user-scoped Intervals sync/i);
  assert.match(syncStatusSource, /getSyncHealthSummary/i);
  assert.match(syncStatusSource, /Latest worker update/i);
  assert.match(syncStatusSource, /Snapshot freshness/i);
  assert.match(syncStatusSource, /Open configuration/i);
  assert.match(syncStatusSource, /resave the connection to restart sync/i);
  assert.match(syncHealthSource, /deriveSyncHealthLabel/i);
  assert.match(syncHealthSource, /freshnessStateFromSnapshot/i);
  assert.match(syncHealthSource, /Stale \(|Aging \(|Fresh \(/i);
  assert.match(syncHealthSource, /Sync failed|Sync running|Sync queued|Waiting for first snapshot/i);
  assert.match(syncHealthSource, /Last snapshot/i);
  assert.match(syncHealthSource, /Last worker update/i);
  assert.match(syncHealthSource, /Ready/i);
  assert.match(admin, /redirect\(\`\$\{appRoutes\.account\}\?tab=user-management\`\)/i);
  assert.match(inviteCreateRoute, /accountInvitesUrl\('notice'|tab=invites&\$\{messageKey\}/i);
  assert.match(inviteCreateRoute, /recipientName/i);
  assert.match(inviteCreateRoute, /recipientEmail/i);
  assert.match(inviteRevokeRoute, /accountInvitesUrl\('notice'|tab=invites&\$\{messageKey\}/i);
  assert.doesNotMatch(intervalsConnectPanel, /dev scaffold flow/i);
  assert.doesNotMatch(intervalsConnectPanel, /api_key=demo-key/i);
  assert.match(intervalsConnectPanel, /Intervals is mandatory in v1/i);
  const routesSource = await readFile(join(webRoot, 'lib/routes.ts'), 'utf8');
  const planRacesPageSource = await readFile(join(webRoot, 'app/app/plan/races/page.tsx'), 'utf8');
  assert.doesNotMatch(routesSource, /styleGuide:\s*'\/app\/style-guide'/i);
  assert.doesNotMatch(routesSource, /analysis:\s*'\/app\/analysis'/i);
  assert.doesNotMatch(routesSource, /workouts:\s*'\/app\/workouts'/i);
  assert.match(routesSource, /planRaces:\s*'\/app\/plan\/races'/i);
  assert.doesNotMatch(account, /tab === 'intervals'/i);
  assert.doesNotMatch(planRacesPageSource, /Open style guide/i);
});
