export const appRoutes = {
  landing: '/',
  login: '/login',
  register: '/register',
  onboardingIntervals: '/onboarding/intervals-connect',
  onboardingSync: '/onboarding/sync-status',
  dashboard: '/app/dashboard',
  plan: '/app/plan',
  planRaces: '/app/plan/races',
  styleGuide: '/app/style-guide',
  analysis: '/app/analysis',
  calendar: '/app/calendar',
  workouts: '/app/workouts',
  account: '/app/account',
  admin: '/app/admin',
};
